vehicle:
  year: 2018
  make: Toyota
  model: Camry
  vin: ''
thresholds:
  miles: 500
  days: 30
tasks:
- name: 15,000 mile service performed
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: 20,000 mile service performed
  interval_miles: null
  interval_months: 12
  initial_miles: 11154
  initial_date: '1970-01-01'
- name: 25,000 mile service performed
  interval_miles: null
  interval_months: 12
  initial_miles: 15121
  initial_date: '1970-01-01'
- name: Air filter replaced
  interval_miles: null
  interval_months: 12
  initial_miles: 19800
  initial_date: '1970-01-01'
- name: Antifreeze/coolant checked
  interval_miles: 100000
  interval_months: 120
  initial_miles: 46544
  initial_date: '1970-01-01'
- name: Antifreeze/coolant flushed/changed
  interval_miles: 100000
  interval_months: 120
  initial_miles: 25442
  initial_date: '1970-01-01'
- name: Brake fluid flushed/changed
  interval_miles: 30000
  interval_months: 36
  initial_miles: 25442
  initial_date: '1970-01-01'
- name: Brakes checked
  interval_miles: null
  interval_months: 12
  initial_miles: 44000
  initial_date: '1970-01-01'
- name: Cabin air filter replaced/cleaned
  interval_miles: 15000
  interval_months: 12
  initial_miles: 44000
  initial_date: '1970-01-01'
- name: Cooling system checked
  interval_miles: null
  interval_months: 12
  initial_miles: 46544
  initial_date: '1970-01-01'
- name: Fluids checked
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Front wiper blades/refills replaced
  interval_miles: null
  interval_months: 12
  initial_miles: 25100
  initial_date: '1970-01-01'
- name: Maintenance inspection completed
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Mirror(s) checked
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Nitrogen fill tires
  interval_miles: null
  interval_months: 12
  initial_miles: 4
  initial_date: '1970-01-01'
- name: Oil and filter changed
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Paint protection applied
  interval_miles: null
  interval_months: 12
  initial_miles: 4
  initial_date: '1970-01-01'
- name: Pre-delivery inspection completed
  interval_miles: null
  interval_months: 12
  initial_miles: 4
  initial_date: '1970-01-01'
- name: Safety inspection performed
  interval_miles: null
  interval_months: 12
  initial_miles: 19800
  initial_date: '1970-01-01'
- name: Tire condition and pressure checked
  interval_miles: null
  interval_months: 12
  initial_miles: 4
  initial_date: '1970-01-01'
- name: Tires rotated
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Vehicle serviced
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Vehicle washed/detailed
  interval_miles: null
  interval_months: 12
  initial_miles: 0
  initial_date: '1970-01-01'
- name: Wheel locks installed
  interval_miles: null
  interval_months: 12
  initial_miles: 4
  initial_date: '1970-01-01'
- name: Window tint installed
  interval_miles: null
  interval_months: 12
  initial_miles: 25100
  initial_date: '1970-01-01'
- name: Wiper(s) replaced
  interval_miles: null
  interval_months: 12
  initial_miles: 44000
  initial_date: '1970-01-01'
